In [3]:
import numpy as np

scalar = np.array(0) #안에 들어있는 값
print(f'Scalar value: {scalar}') 
print(f'Rank: {scalar.ndim}, Shape: {scalar.shape}')

Scalar value: 0
Rank: 0, Shape: ()


In [4]:
vector = np.array([0, 1, 2, 3, 4, 5, 6])
print(f'Vector values: {vector}') #벡터는 1차원
print(f'Rank: {vector.ndim}, Shape: {vector.shape}') #shape: 안의 원소

Vector values: [0 1 2 3 4 5 6]
Rank: 1, Shape: (7,)


In [7]:
# (batch, data)
matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
#대괄호 안에 또 대괄호, 대괄호 하나가 벡터하나, 벡터들이 모여서 차원이 증가

print(f'Matrix values: \n{matrix}')
print(f'Rank: {matrix.ndim}, Shape: {matrix.shape}') #2차원

Matrix values: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Rank: 2, Shape: (3, 3)


In [8]:
# (batch, width, height)
tensor = np.array([[[0, 1], [2, 3], [4, 5]], [[6, 7], [8, 9], [10, 11]]]) #2차원짜리 2개
print(f'Tensor values: \n{tensor}')
print(f'Rank: {tensor.ndim}, Shape: {tensor.shape}')

Tensor values: 
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Rank: 3, Shape: (2, 3, 2)


In [10]:
# (batch, width, height)

#2차원짜리 3개 -> rank:3
tensor = np.array([[[0, 1], [2, 3], [4, 5]], [[6, 7], [8, 9], [10, 11]], [[12, 13],[14,15],[16,17]]])
print(f'Tensor values: \n{tensor}')
print(f'Rank: {tensor.ndim}, Shape: {tensor.shape}') #shape(겹쳐진 행렬의 수(1), 행렬의 모양(2,3))

Tensor values: 
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
Rank: 3, Shape: (3, 3, 2)


In [16]:
# torch-based Tensor
import torch

t = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]]) #3개의 벡터, rank 2 tensor
print(f'Tensor values: \n{t}')
print(f't[0]: {t[0]}, t[-1]: {t[-1]}') #행렬의 0번째 요소, 맨 마지막 요소(-1)를 출력
print(f't[:2]: {t[:2]}') #tensor의 2번째 요소까지 자름: 0, 1 출력
print(f't[1:]: {t[1:]}') #tensor의 1번째 요소부터: 1, 2 출력
print(f'Rank: {t.dim()}, Shape: {t.shape}')

Tensor values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
t[0]: tensor([0, 1, 2]), t[-1]: tensor([6, 7, 8])
t[:2]: tensor([[0, 1, 2],
        [3, 4, 5]])
t[1:]: tensor([[3, 4, 5],
        [6, 7, 8]])
Rank: 2, Shape: torch.Size([3, 3])


In [17]:
#3차원 tensor

t = torch.tensor([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],[[0, 1, 2], [2, 3, 4], [5, 6, 7]]])
print(f'Tensor values: \n{t}')
print(f't[0]: {t[0]}, t[-1]: {t[-1]}')
print(f't[:2]: {t[:2]}')
print(f't[1:]: {t[1:]}')
print(f'Rank: {t.dim()}, Shape: {t.shape}')

Tensor values: 
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [2, 3, 4],
         [5, 6, 7]]])
t[0]: tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), t[-1]: tensor([[0, 1, 2],
        [2, 3, 4],
        [5, 6, 7]])
t[:2]: tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [2, 3, 4],
         [5, 6, 7]]])
t[1:]: tensor([[[0, 1, 2],
         [2, 3, 4],
         [5, 6, 7]]])
Rank: 3, Shape: torch.Size([2, 3, 3])


In [22]:
# Broadcasting
# Same shape
print(torch.tensor([1, 4]) + torch.tensor([2, -1]))

# Vector + Scalar
print(torch.tensor([1, 4]) + torch.tensor([3]))

print(torch.tensor([2, 2]) + torch.tensor([3]))
# 3 -> [3, 3,]

# 1 x 2 vector + 2 x 1 vector
print(torch.tensor([1, 2]) + torch.tensor([[3], [4]]))
#차원 모양이 다른 것들을 더 하면 예상하지 못하는 모양이 나올 수 있음

# 1 x 2 vector + 2 x 1 vector
print(torch.tensor([1, 4]) + torch.tensor([[7], [7]]))

tensor([3, 3])
tensor([4, 7])
tensor([5, 5])
tensor([[4, 5],
        [5, 6]])
tensor([[ 8, 11],
        [ 8, 11]])


In [23]:
# Matrix multiplication vs. Elementwise multiplication
m1 = torch.tensor([[1, 2], [3, 4]]) # 2 x 2
m2 = torch.tensor([[1], [2]]) # 2 x 1
print(m1.shape, m2.shape)

#[1*1 + 2*2], [3*1 + 4*2]
print(f'Matrix multiplication: \n{m1.matmul(m2)} \n{m1 @ m2}') 

#[1, 2]에는 1이 곱함, [3, 4]에는 2가 곱함
print(f'Elementwise multiplication: \n{m1.mul(m2)} \n{m1 * m2}')

torch.Size([2, 2]) torch.Size([2, 1])
Matrix multiplication: 
tensor([[ 5],
        [11]]) 
tensor([[ 5],
        [11]])
Elementwise multiplication: 
tensor([[1, 2],
        [6, 8]]) 
tensor([[1, 2],
        [6, 8]])


In [24]:
# Mean and Standard deviation # Cannot be calculated on integers
t = torch.tensor([[1., 2.], [3., 4.]])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.std())

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor(1.2910)


In [25]:
# Summation
t = torch.tensor([[1., 2.], [3., 4.]])
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


In [26]:
# Max and Argmax
t = torch.tensor([[1., 2.], [3., 4.]])
print(t.max())
# With specified dimension, the first is the maximum
# and the second is the argmax.
#dim 차원 지정해서 최댓값 출력

#dim=0 은 행따라 출력
print(f'Max: {t.max(dim=0)[0]}, Argmax: {t.max(dim=0)[1]}') #Argmax 가장 큰 값이 있는 위치 반환

#dim=1은 열따라 출력
print(f'Max: {t.max(dim=1)[0]}, Argmax: {t.max(dim=1)[1]}')

tensor(4.)
Max: tensor([3., 4.]), Argmax: tensor([1, 1])
Max: tensor([2., 4.]), Argmax: tensor([1, 1])


In [33]:
# Max and Argmax
t = torch.tensor([[1., 2.], [3., 4.]])
print(t.max()) #최댓값 출력
# With specified dimension, the first is the maximum
# and the second is the argmax.
print(f'Max: {t.max(dim=0)[1]}, Argmax: {t.max(dim=0)[1]}')
print(f'Max: {t.max(dim=1)[0]}, Argmax: {t.max(dim=1)[1]}')

tensor(4.)
Max: tensor([1, 1]), Argmax: tensor([1, 1])
Max: tensor([2., 4.]), Argmax: tensor([1, 1])


In [34]:
# View (reshape) #reshape와 비슷, 모양이 달라짐. 상상과 달라질 때가 있음
t = torch.tensor([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]]) 
#두개의 tensor가 따로 행렬로 묶어져 있음
print(t.shape)

#여기서 -1은 남는 숫자 아무거나 넣어달라
print(t.view([-1, 3])) # '-1' for automatic calculation.
print(t.view([-1, 3]).shape)

print(t.view([-1, 1, 3]))
print(t.view([-1, 1, 3]).shape)

torch.Size([2, 2, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([4, 3])
tensor([[[ 0,  1,  2]],

        [[ 3,  4,  5]],

        [[ 6,  7,  8]],

        [[ 9, 10, 11]]])
torch.Size([4, 1, 3])


In [36]:
# 6*3
t = torch.tensor([[[0, 1, 2], [3, 4, 5]], 
                  [[6, 7, 8], [9, 10, 11]], 
                  [[12, 13, 14],[15, 16, 17]]])
print(t.shape)

#여기서 -1은 남는 숫자 아무거나 넣어달라
print(t.view([-1, 3])) # '-1' for automatic calculation.
print(t.view([-1, 3]).shape)

print(t.view([-1, 1, 3])) #중간에 차원이 하나씩 추가 됨
print(t.view([-1, 1, 3]).shape) # [3, 2, 3]에서 [6, 1, 3]이 됨

torch.Size([3, 2, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([6, 3])
tensor([[[ 0,  1,  2]],

        [[ 3,  4,  5]],

        [[ 6,  7,  8]],

        [[ 9, 10, 11]],

        [[12, 13, 14]],

        [[15, 16, 17]]])
torch.Size([6, 1, 3])


In [37]:
# Squeeze
t = torch.tensor([[0], [1], [2], [3]]) #불필요하게 하나씩 더 들어가있ㅇ름
print(t)
print(t.shape)
print(t.squeeze())
print(t.squeeze().shape)

tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([4, 1])
tensor([0, 1, 2, 3])
torch.Size([4])


In [40]:
# Squeeze
t = torch.tensor([1, 2, 3, 4]) #불필요하게 하나씩 더 들어가있음 없애주면 어떻게 결과 달라지는지
print(t)
print(t.shape)
print(t.squeeze())
print(t.squeeze().shape)

tensor([1, 2, 3, 4])
torch.Size([4])
tensor([1, 2, 3, 4])
torch.Size([4])


In [38]:
# Squeeze
t = torch.tensor([[0, 3]]) #불필요하게 하나씩 더 들어가있ㅇ름
print(t)
print(t.shape)
print(t.squeeze())
print(t.squeeze().shape)

tensor([[0, 3]])
torch.Size([1, 2])
tensor([0, 3])
torch.Size([2])


In [41]:
# Concatenation 모양을 바꾸는 연산
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[5, 6], [7, 8]])
print(torch.cat([t1, t2], dim=0)) # 4 x 2
print(torch.cat([t1, t2], dim=1)) # 2 x 4

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [42]:
# Stacking 모양을 바꾸는 연산
t1 = torch.tensor([1, 4])
t2 = torch.tensor([2, 5])
t3 = torch.tensor([3, 6])
print(torch.stack([t1, t2, t3])) # 3 x 2
print(torch.stack([t1, t2, t3], dim=1)) # 2 x 3

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [43]:
# Ones and Zeros
t = torch.tensor([[3, 1, -2], [5, 0, 4]])
print(t.shape)

print(torch.ones_like(t)) #[2,3]으로 된 1로 이루어진 tensor가 나옴
print(torch.zeros_like(t)) #[2, 3]으로 된 0으로 이루어진 tensor가 나옴
#딥러닝 할 때는 이런 0, 1로 이루어진 tensor들을 사용할 일이 많음

torch.Size([2, 3])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [44]:
# Ones and Zeros
t = torch.tensor([[3, 1], [5, 0]]) #모양을 다르게 해도 됨
print(t.shape)
print(torch.ones_like(t))
print(torch.zeros_like(t))

torch.Size([2, 2])
tensor([[1, 1],
        [1, 1]])
tensor([[0, 0],
        [0, 0]])


In [45]:
# Ones and Zeros
t = torch.tensor([[3, 1, 100], [5, 90, 4]]) #내용이 어떻든 모양만 잘 잡아줌
print(t.shape)
print(torch.ones_like(t))
print(torch.zeros_like(t))

torch.Size([2, 3])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [49]:
# In-place Operation
t = torch.tensor([[1., 2.], [3., 4.]])
print(t.mul(2.)) #2를 모든 원소에 곱해준다
print(t) #처음에 선언된 t가 유지됨

print(t.mul(6.)) #각 원소에 6씩 곱하고
print(t) #처음 t 유지

print(t.mul_(2.)) #t에 mul_하면 유지를 해줌
print(t) #그대로 남아있음을 볼 수 있음

print(t.mul_(6.)) #t에 mul_하면 유지를 해줌
print(t) #그대로 남아있음을 볼 수 있음

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 6., 12.],
        [18., 24.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[12., 24.],
        [36., 48.]])
tensor([[12., 24.],
        [36., 48.]])
